### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by as-cii**
### Description of the Change

In an attempt to make tests more reliable, I have decaffeinated spell-checks-spec.coffee, so that I could use `async`/`await` which, other than looking prettier, are hopefully more reliable than the equivalent CoffeeScript code.

### Applicable Issues

https://github.com/atom/spell-check/issues/239

### CODE REVIEW

**Comment by as-cii** [comment]
@lee-dohm: I have rebuilt this branch three times and tests seem to be much more reliable (I haven't observed any failure).

@maxbrunsfeld: can I talk you into taking a look at the TODO above? It seems like tree-sitter parsers are enabled by default on master and they are breaking spell-check because it still relies on legacy scope names to decide which grammars and syntactic constructs to spell-check.

**Comment by maxbrunsfeld** [comment]
> It seems like tree-sitter parsers are enabled by default on master

They're [not enabled by default](https://github.com/atom/atom/blob/master/src/config-schema.js#L354-L357), but it looks like there's a bug that causes the tests to read your `config.cson` 😱  https://github.com/atom/atom/issues/16910. I'll look into that asap.

**Comment by as-cii** [comment]
Thanks for jumping on that, @maxbrunsfeld. ✨ I'll go ahead and merge this pull request after reverting 30f0e9d. As for spell-check not working when tree-sitter is on, I am going to ignore that issue for the time being as I assume you were already aware of it.

**Comment by lee-dohm** [comment]
Thanks @maxbrunsfeld and @as-cii :bow: This is great!

**Comment by maxbrunsfeld** [comment]
> As for spell-check not working when tree-sitter is on, I am going to ignore that issue for the time being as I assume you were already aware of it.

I think it was just a problem with the spell-check tests. They enabled spell-check for the `source.js` scope and assumed that opening a file ending in `.js` would use that scope, but it actually used the `javascript` scope.

**Comment by as-cii** [comment]
> I think it was just a problem with the spell-check tests. They enabled spell-check for the source.js scope and assumed that opening a file ending in .js would use that scope, but it actually used the javascript scope.

Interesting. The main reason why I pointed that out was that after looking at the following lines of code:

* https://github.com/atom/spell-check/blob/1106cfd7b0154c775c37054ccd2b04c689f1f0f4/lib/spell-check-view.coffee#L73-L75
* https://github.com/atom/spell-check/blob/1106cfd7b0154c775c37054ccd2b04c689f1f0f4/lib/spell-check-view.coffee#L175-L179

It seemed like the config settings could refer to the legacy scope names, which would not work when tree-sitter is on. What am I missing?

**Comment by maxbrunsfeld** [comment]
Yeah, that's right. If someone actually wanted to spell-check a language e.g. JavaScript for some reason, right now they'd have to add `javascript` to their scopes setting rather than `source.js`; I haven't added logic to Spell-check for dealing with the equivalent scopes. I thought you were saying there was some other sort of breakage in the package due to Tree-sitter.

**Pull request merged**
