### PR TITLE
Add text.md to grammars list

### PR DESCRIPTION
**Pull request by twellspring**
Enable spelling for the language-markdown language, which replaces language-gfm.

### CODE REVIEW

**Comment by bbodenmiller** [comment]
I'm already getting spell check with `.md` it seems. See #144.

**Comment by twellspring** [comment]
Spell checking only worked for me if I had `Github Markdown` as the type for my .md files.  When I disabled Github Markdown and used only the default Markdown as the type for my .md files I did not get spell checking.

Since Markdown is now the default with a new Atom install, it is likely that new users will not have the GHM installed.  Adding the `text.md` to the default list will provide spell checking for these new users by default while leaving the legacy `sources.gfm` in the list means existing users using Github Markdown will keep the spell check functionality.

**Comment by 50Wliu** [comment]
> Since Markdown is now the default with a new Atom install

Can you clarify?  GitHub Markdown is still the default (and Markdown is not installed with Atom).  How are you installing Atom?

**Comment by twellspring** [comment]
I am running it on MacOS ... Think I downloaded the zip file from the atom  homepage, but not totally sure.   I would have to try to re-construct a debugging session to find where I read about language-gfm not being the default any more.     if language-gfm is really still the default then the reason to do this pull request would be to allow uses with only language-markdown to get spell check by default.

**Comment by burodepeper** [comment]
As the author of `language-markdown` I wanted to submit this path too (as a result of https://github.com/burodepeper/language-markdown/issues/134), so I'm just here giving this my :+1:.

#144 seems an equally valid solution, though I prefer the `text.md` scope.

**Comment by twellspring** [comment]
Looks like this is not going to get approved/merged so I am closing

**Pull request closed without merging**
