### PR TITLE
Performance fixes

### PR DESCRIPTION
**Pull request by damieng**
There exists a bug in node that means the IPC queue suffers big performance issues when the data in the queue is large. It is fixed in node 7.5.0 but that will not ship until electron 1.7.x or later which Atom is not yet ready for.

As the spell check package currently sends the complete text for all open files on start-up even a few reasonably small files can cause the editor to hang for some time because of the issue. #190 

This change queues the spell check changes up and ensures only one for each editor is in the queue at a time, this helps in that:

1. Requests are not all thrown into the queue at the same time but rather serialized - preventing the buffer from getting too large with multiple small files.
2. Prevents a large backlog of requests when editing single larger files by removing an as-yet-unstarted spell-check request for a buffer when adding one.

Some additional things we could do to further improve things:

1. Switch to web workers instead of child process - would allow the buffer text to avoid serialization
2. Prioritize active and visible editors in the queue for better apparent responsiveness

Paired with @smashwilson

### CODE REVIEW

**Comment by smashwilson** [comment]
> Switch to web workers instead of child process - would allow the buffer text to avoid serialization

I started to implement this, but on @maxbrunsfeld's recommendation, I've instead introduced an [asynchronous `check` method to the native spellchecker](https://github.com/atom/node-spellchecker/pull/75). That eliminates the need for `Tasks` altogether (whether process- or WebWorker-backed) by doing the sidecar work in a C++ thread.

I've cleaned out some of the relics of the `Task` approach along the way, like needing to pass IPC messages around when the Atom config changes. There are still some things that could be cleaned out and simplified now, but I'll resist the urge to do any more drastic changes as part of this work.

> Prioritize active and visible editors in the queue for better apparent responsiveness

I'll tackle this next.

**Comment by maxbrunsfeld** [comment]
:zap: So happy you guys fixed these perf issues.

**Comment by smashwilson** [comment]
And the tests are green 🙌 

@ungb, when you have the time, would you mind verifying that these fixes are sufficient? Just so that we have some additional assurance beyond "it works on my computer" 😅 (Especially since @damieng's machine is an absolute beast!)

**Comment by damieng** [comment]
Nice job Ash!

**Comment by ungb** [comment]
I saw that this fixed the issue where atom freezes up ❇️ ! I didn't see any issues, but I saw that atom does still consume a lot of memory but not as much as before.
I only tested on windows. LGTM to merge!
image

**Comment by damieng** [comment]
@ungb How much memory does Atom use if you open the same files but with Spell Check turned off?

**Comment by ungb** [comment]
it's still relatively high but maybe half with spell check turned off.

image

**Comment by smashwilson** [comment]
Hmm okay. I'm guessing that means we're still duplicating the buffer text when we spellcheck.

**Comment by smashwilson** [comment]
:shipit: in :atom: as 0.72.0!

There _is_ likely a long tail of other improvements we could make here, performance- and memory-wise 🤔  This should at least address the lockups.

**Comment by maxbrunsfeld** [comment]
We should expect the text to get duplicated once while the spell check is running, right? Because the text is copied from the JS string into a `std::vector`. But that's no worse than what we were doing before, where we would copy the text into a whole other *process* via IPC.

**Pull request merged**
