### PR TITLE
Decaffinate project into Javascript

### PR DESCRIPTION
**Pull request by dmoonfire**
- Added Prettier to give a baseline for formatting.
- Added Husky to ensure consistency with formatting.

### Description of the Change

While the tests had already been converted from Coffescript to Javascript but the main library was still Coffescript. This PR migrates everything else to Javascript. It also added Prettier and Husky to ensure consistent formatting.

### Alternate Designs

The alternative is to keep it Coffeescript. This PR was created because it seems like Atom is moving toward Javascript and it requires only one language to develop.

### Benefits

- Consistent language (Javascript) as opposed to two languages with development.
- Consistent formatting to simplify pull requests.

### Possible Drawbacks

- There is a possibility that there will be a scope issue that was missed as part of the conversion. All the tests run cleanly.

### Applicable Issues

- None

### CODE REVIEW

**Comment by dmoonfire** [comment]
I have a bit of code clean up that I missed (decaffinate comments).

**Comment by dmoonfire** [comment]
Okay, everything is cleaned up. It's ready for review and works through my test cases.

@lkashef, would you be a good person to start looking at this for me?

**Comment by 9994444ggg** [comment]
Thank You for write me

**Comment by the-j0k3r** [comment]
This is a great step, so congrats, I cant see that `coffelint.json` was left and no JS linting added + such `coffeelint.json` references in `package.json` devdepencencies also there. I presume these will be added?

**Comment by dmoonfire** [comment]
> Was the `coffeelint.json` removed? Its should have been removed but cant see where the deletion is.

I missed that, thank you, @the-j0k3r. I force pushed the commit to include it.

**Comment by dmoonfire** [comment]
@sadick254, I fixed the conflicts from the last release on this.

**Review by sadick254 — APPROVED** [review]
This looks great. Thanks @dmoonfire

**Pull request merged**
