### PR TITLE
Use fork of spelling-manager module that omits webworker-threads 

### PR DESCRIPTION
**Pull request by jasonrudolph**
#244 attempted to resolve the issue reported in https://github.com/atom/spell-check/issues/67#issuecomment-377808833. As described in https://github.com/atom/spell-check/pull/244#issuecomment-380584223, the changes in #244 didn't have the desired effect. This pull request opts for an alternative approach:

- Revert #244 (1e33fac74380895858b61b994d383005c1693933)
- Use a fork of the spelling-manager module that doesn't include the problematic webworker-threads module (f16dc17de82d7d58b034b710c676e60355f6da4b)

### Approach

1. Create a fork of the natural module and remove the optional dependency on the webworker-threads module, which [doesn't play nicely with Electron](https://github.com/NaturalNode/natural/issues/368). (https://github.com/atom/natural/commit/f46f280a2d32245152727f2a2b0e2bb3c7dbb542)
2. Create a fork of the spelling-manager module and update it to depend on our fork of the natural module. (https://github.com/atom/spelling-manager-js/commit/51fbf53ce13150170d1073585450e1450acbd917)
3. Update the spell-check package to depend on our fork of the spelling-manager module. (f16dc17de82d7d58b034b710c676e60355f6da4b)

We'd prefer not to have to maintain these forks long-term, especially since @dmoonfire already has [plans to remove the webworker-threads dependency from the spelling-manager module](https://github.com/dmoonfire/spelling-manager-js/issues/4). (Thanks, @dmoonfire! 💟) In the meantime, these forks should give us a pragmatic way to resolve the issue reported in https://github.com/atom/spell-check/issues/67#issuecomment-377808833 before Atom 1.26 graduates from beta to stable in the next few weeks. :sweat_smile:

### CODE REVIEW

**Comment by dmoonfire** [comment]
You probably don't need to fork `natural`. I was only using it for a tokenizer. That should be simple enough to implement that specific class in spelling-manager. And if you do it as a PR for spelling-manager-js, I'll be glad to help and/or merge it. My next week is already dedicated to Atom spelling issues, so I have the bandwidth to assist.

**Comment by jasonrudolph** [comment]
> You probably don't need to fork `natural`. I was only using it for a tokenizer. That should be simple enough to implement that specific class in spelling-manager. 

@dmoonfire: We're under a bit of a time crunch. 😬 We're likely to publish Atom 1.26 early next week, and I want to find a fix for the [webworker-threads issue](https://github.com/atom/spell-check/issues/67#issuecomment-377808833) prior to that release. Removing spelling-manager's dependency on the natural module is probably not something we'll have time to tackle prior to the Atom 1.26 release.

As an alternative to this pull request, would you be willing to merge https://github.com/dmoonfire/spelling-manager-js/pull/5 and publish a new version of spelling-manager containing that change? If so, I'll update the spell-check package to depend on that new version of the spelling-manager module, and I'll close this pull request.

**Comment by dmoonfire** [comment]
I merged and pushed up a new version (1.1.0), want to try it?

**Comment by jasonrudolph** [comment]
> I merged and pushed up a new version (1.1.0), want to try it?

@dmoonfire: Thanks for the lightning-fast turnaround. :zap:

#246 upgrades spell-check to spelling-manager 1.1.0. I'll publish a new version of the spell-check package shortly and update atom/atom to use the new version.

**Pull request closed without merging**
