### PR TITLE
Dictionary selection

### PR DESCRIPTION
**Pull request by krzychu**
This change makes it possible to change spellchecker language from package settings - #11. Works on Ubuntu, and I don't have other systems to check it on.

### CODE REVIEW

**Comment by lee-dohm** [comment]
This would need specs before it could be accepted. Also, I'm a bit concerned that there is a default in a setting that has no relevance on the majority of systems.

**Comment by krzychu** [comment]
On systems using hunspell those settings should have default values (as they do now, but that's hidden in the library), and on other systems they should be disabled or invisible. There seems to be no way of dynamically hiding and removing settings based on platform, so in my opinion next best thing would be to name those parameters something like "Hunspell Language" and "Hunspell Language Directory". What do you think?

**Comment by getreu** [comment]
This is tagged "needs-testing". Any update here?
What is the blocker? Can I help testing?

**Comment by jcharest** [comment]
I have been using this feature for a while now: Linux with fr_CA. It is working.

**Comment by CostGranda** [comment]
How can be test it on Windows Systems?

**Comment by Paviluf** [comment]
I really hope that this PR will be implemented soon because it's so annoying for non english speakers that can't use spell check in their language. I'm surprised that this is not a priority.

Thanks !

**Comment by JanFrydrych** [comment]
Hi,
is there a faster way to change language than changing locales in spell-check package settings? Perhaps from command palette or from status bar like grammar selector?

**Pull request closed without merging**
