### PR TITLE
Add reStructuredText to default spell checked formats

### LINKED ISSUE #209: .rst (restructuredText) files are not recognized by default
[`.rst`](https://atom.io/packages/language-restructuredtext) is a very common file format and used for docs, just like `.md` (markdown). Both of them should be spellchecked by default, without needing any further modifications.

It seems that adding these values should fix the issue: `source.rst` and `text.restructuredtext`

### PR DESCRIPTION
**Pull request by jessetan**
### Description of the Change

Adds reStructuredText to the grammars that are spell checked by default. Since the format has a similar text vs markup ratio as markdown and asciidoc, adding rst to spell checking seems logical.

### Applicable Issues

Fixes #209

### CODE REVIEW

**Comment by borisalmonacid** [comment]
it's ok?

**Comment by dmoonfire** [comment]
This needs to be brought up to date with some changes in the core Atom logic. If @jessetan doesn't, I'll look at it as part of my queue.

**Comment by jessetan** [comment]
Merged master into the branch without conflicts. I don't see anything else to update, so I'd appreciate it if @dmoonfire can take a look.

**Comment by borisalmonacid** [comment]
thanks :)

**Pull request merged**
