### PR TITLE
Add feature: toggle on/off

### PR DESCRIPTION
**Pull request by roccosportal**
I added the feature 'Toggle' to the 'Packages -> Spell Check' menu. I had a look at https://github.com/fundon/atom-minimap for the implemenation. A review would be nice, since I'm new to atom and not very good in coffeescript.

### CODE REVIEW

**Comment by karlek** [comment]
Any update on this?

**Comment by pwaller** [comment]
Ping. I just wanted to edit a tech document document and everything has been highlighted. It's very distracting and I want to turn it off.

**Comment by roccosportal** [comment]
Well I updated the code.  Merging is off my hands.

**Comment by thedaniel** [comment]
This still needs a spec, then it can be merged.

**Comment by roccosportal** [comment]
"spec" stands for specification? I'm not sure what you mean. Any references how the specification should look like? We are talking about a toggle on/off feature, what should I specify? Thanks!

**Comment by 50Wliu** [comment]
@roccosportal a "spec" is something that tests this behavior to make sure it doesn't break in the future.  See the `specs` folder for some examples and the [specs styleguide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#specs-styleguide) for more pointers.

**Comment by roccosportal** [comment]
Alright, I will look into it. But I'm going on vacation now, anyone feel free to write a spec.

**Comment by maxcnunes** [comment]
Hi,

This is a pretty useful feature. Good job @roccosportal!! I'm trying to create the tests for it.
I'm just confused how to apply my changes to this pull request. Do I have to send the pull request to `roccosportal/spell-check:master`?

**Comment by maxcnunes** [comment]
I sent the test to @roccosportal's fork. That seems the right approach. But since he is on vocation I'm not sure he is going to be able merging it soon.

**Comment by maxcnunes** [comment]
@kevinsawicki any plan merging it to master?

**Comment by jehrhardt** [comment]
@roccosportal: There are some conflicts that need to be resolved before merge.

Btw. great work :+1:.

**Comment by roccosportal** [comment]
Did the merge and updated the toggle off spec.

**Comment by jehrhardt** [comment]
@kevinsawicki Is there anything to do before this can be merged?

**Comment by thedaniel** [comment]
This looks great. I think that `@subscriptionsOfCommands` should be `@commandSubscriptions` but in the interest of diminishing back-and-forth, I'll just change that in a separate PR.

**Comment by 0mp** [comment]
When will this feature be available in Atom? I cannot find it.

**Comment by thedaniel** [comment]
It's only just made it into the Atom 1.7 beta release, which will probably become stable in a few weeks, but there's no set release date.

**Comment by xenomode** [comment]
I'm still not seeing this available in Atom 1.11.2

**Comment by 0mp** [comment]
@xenomode Click **Packages** > **Command Palette** > **Toggle** and search for _Spell Check: Toggle_.

**Pull request merged**
